import type { Risk, TreatmentAction } from "./types";

export const SEED_RISKS: Risk[] = [
  {
    id: "R-001",
    category: "Операционный",
    name: "Сбой ключевого производственного оборудования",
    cause: "Износ оборудования, отсутствие планового ТО",
    consequence: "Остановка производства, срыв поставок",
    owner: "Директор по производству",
    dateFound: "2026-01-15",
    inherentProbability: 4,
    inherentImpact: 4,
    existingControls: "Плановое ТО раз в квартал, резервное оборудование",
    controlEffectiveness: "Частично эффективен",
    residualProbability: 3,
    residualImpact: 3,
    strategy: "Снижение",
    status: "В работе",
    nextReviewDate: "2026-09-01",
  },
  {
    id: "R-002",
    category: "Финансовый",
    name: "Валютный риск при закупках в иностранной валюте",
    cause: "Колебания курса USD/EUR при импорте сырья",
    consequence: "Рост себестоимости, снижение маржи",
    owner: "Финансовый директор",
    dateFound: "2026-02-01",
    inherentProbability: 4,
    inherentImpact: 3,
    existingControls: "Частичное валютное хеджирование форвардными контрактами",
    controlEffectiveness: "Эффективен",
    residualProbability: 2,
    residualImpact: 3,
    strategy: "Снижение",
    status: "Под контролем",
    nextReviewDate: "2026-08-15",
  },
  {
    id: "R-003",
    category: "Комплаенс",
    name: "Несоответствие требованиям законодательства о персональных данных",
    cause: "Устаревшие процедуры обработки ПДн, отсутствие обучения персонала",
    consequence: "Штрафы регулятора, репутационные потери",
    owner: "Руководитель службы комплаенс",
    dateFound: "2026-01-20",
    inherentProbability: 3,
    inherentImpact: 4,
    existingControls: "Политика обработки ПДн, назначен ответственный (DPO)",
    controlEffectiveness: "Частично эффективен",
    residualProbability: 1,
    residualImpact: 3,
    strategy: "Снижение",
    status: "В работе",
    nextReviewDate: "2026-07-30",
  },
  {
    id: "R-004",
    category: "HR (кадровый)",
    name: "Отток ключевых сотрудников",
    cause: "Недостаточная конкурентоспособность оплаты труда, отсутствие карьерных треков",
    consequence: "Потеря экспертизы, рост затрат на найм и адаптацию",
    owner: "HR-директор",
    dateFound: "2026-02-10",
    inherentProbability: 4,
    inherentImpact: 4,
    existingControls: "Программа удержания, регулярный обзор заработных плат",
    controlEffectiveness: "Частично эффективен",
    residualProbability: 3,
    residualImpact: 3,
    strategy: "Снижение",
    status: "Открыт",
    nextReviewDate: "2026-10-01",
  },
  {
    id: "R-005",
    category: "ИБ (информационная безопасность)",
    name: "Утечка конфиденциальных данных вследствие кибератаки",
    cause: "Уязвимости периметровой защиты, фишинговые атаки на сотрудников",
    consequence: "Утрата данных, штрафы регулятора, репутационный ущерб",
    owner: "Директор по ИБ (CISO)",
    dateFound: "2026-01-25",
    inherentProbability: 4,
    inherentImpact: 5,
    existingControls: "SIEM-система, обучение сотрудников, многофакторная аутентификация",
    controlEffectiveness: "Эффективен",
    residualProbability: 2,
    residualImpact: 3,
    strategy: "Снижение",
    status: "В работе",
    nextReviewDate: "2026-07-15",
  },
  {
    id: "R-006",
    category: "Стратегический",
    name: "Потеря доли рынка из-за выхода нового конкурента",
    cause: "Появление технологичного конкурента с более низкой ценой",
    consequence: "Снижение выручки, отток клиентов",
    owner: "Генеральный директор",
    dateFound: "2026-02-05",
    inherentProbability: 3,
    inherentImpact: 3,
    existingControls: "Мониторинг конкурентной среды, программа лояльности клиентов",
    controlEffectiveness: "Частично эффективен",
    residualProbability: 2,
    residualImpact: 2,
    strategy: "Принятие",
    status: "Открыт",
    nextReviewDate: "2026-12-01",
  },
  {
    id: "R-007",
    category: "Проектный",
    name: "Срыв сроков запуска ИТ-проекта внедрения ERP-системы",
    cause: "Недооценка сложности интеграции, нехватка квалифицированных ресурсов",
    consequence: "Превышение бюджета, задержка получения выгод от проекта",
    owner: "Руководитель проекта",
    dateFound: "2026-03-01",
    inherentProbability: 4,
    inherentImpact: 3,
    existingControls: "Еженедельный контроль хода проекта, резерв бюджета на риски",
    controlEffectiveness: "Частично эффективен",
    residualProbability: 3,
    residualImpact: 2,
    strategy: "Снижение",
    status: "В работе",
    nextReviewDate: "2026-08-01",
  },
];

export const SEED_ACTIONS: TreatmentAction[] = [
  {
    id: "T-001",
    riskId: "R-001",
    action: "Внедрить систему мониторинга состояния оборудования (IIoT-датчики)",
    owner: "Главный инженер",
    resources: "2 500 000 руб.",
    startDate: "2026-03-01",
    endDate: "2026-08-31",
    kri: "Количество внеплановых простоев в месяц",
    targetResidualLevel: 6,
    status: "В работе",
    progressPct: 40,
    comment: "Пилот запущен на 2 производственных линиях",
  },
  {
    id: "T-002",
    riskId: "R-002",
    action: "Заключить дополнительные форвардные контракты на 70% объёма валютных закупок",
    owner: "Казначей",
    resources: "Внутренние трудозатраты",
    startDate: "2026-02-01",
    endDate: "2026-05-31",
    kri: "Доля захеджированных закупок",
    targetResidualLevel: 4,
    status: "Завершено",
    progressPct: 100,
    comment: "Контракты подписаны с банком-партнёром",
  },
  {
    id: "T-003",
    riskId: "R-003",
    action: "Провести аудит процессов обработки персональных данных и обучить персонал",
    owner: "Ответственный за защиту данных (DPO)",
    resources: "300 000 руб.",
    startDate: "2026-02-01",
    endDate: "2026-06-30",
    kri: "Доля сотрудников, прошедших обучение",
    targetResidualLevel: 3,
    status: "В работе",
    progressPct: 60,
    comment: "Обучение проведено в 3 из 5 подразделений",
  },
  {
    id: "T-004",
    riskId: "R-005",
    action: "Внедрить многофакторную аутентификацию для всех критичных систем",
    owner: "Директор по ИБ (CISO)",
    resources: "1 200 000 руб.",
    startDate: "2026-01-15",
    endDate: "2026-04-30",
    kri: "Доля критичных систем с MFA",
    targetResidualLevel: 6,
    status: "В работе",
    progressPct: 70,
    comment: "Осталось подключить 2 legacy-системы",
  },
  {
    id: "T-005",
    riskId: "R-007",
    action: "Привлечь дополнительного интегратора для критичного модуля ERP",
    owner: "Руководитель проекта",
    resources: "4 000 000 руб.",
    startDate: "2026-03-15",
    endDate: "2026-09-30",
    kri: "% выполнения плана проекта",
    targetResidualLevel: 6,
    status: "Не начато",
    progressPct: 0,
    comment: "Ожидается решение бюджетного комитета",
  },
  {
    id: "T-006",
    riskId: "R-001",
    action: "Создать резервный склад запасных частей для критичного оборудования",
    owner: "Директор по производству",
    resources: "800 000 руб.",
    startDate: "2026-04-01",
    endDate: "2026-07-31",
    kri: "Время восстановления после отказа (MTTR)",
    targetResidualLevel: 6,
    status: "В работе",
    progressPct: 55,
    comment: "",
  },
];
